#!/usr/bin/env python3
"""
PreToolUse hook: enforce commit message rules globally.

Blocks any `git commit` whose message:
  - contains co-author attribution (Co-Authored-By)
  - contains "Generated with" / "Claude Code" / robot emoji
  - has a multiline body (single-line commits only)
  - lacks a conventional-commit type prefix

Rules mirror ~/.claude/skills/commit.md
"""
import json
import re
import sys

CONV_TYPES = r"feat|fix|docs|style|refactor|perf|test|chore|ci|build|revert"

FORBIDDEN_SUBSTRINGS = [
    ("Co-Authored-By", "co-author attribution not allowed"),
    ("Co-authored-by", "co-author attribution not allowed"),
    ("Generated with", "'generated with' attribution not allowed"),
    ("generated with", "'generated with' attribution not allowed"),
    ("Claude Code", "'Claude Code' attribution not allowed"),
    ("\U0001f916", "robot emoji not allowed"),
]


def extract_messages(cmd: str):
    """Pull out commit message bodies from a git commit command."""
    messages = []

    # Heredoc form: <<'EOF' ... EOF  or  <<EOF ... EOF
    for m in re.finditer(r"<<-?\s*'?(\w+)'?\s*\n(.*?)\n\s*\1\b", cmd, re.DOTALL):
        messages.append(m.group(2))

    # -m "..." (double quoted)
    for m in re.finditer(r'-m\s+"((?:[^"\\]|\\.)*)"', cmd):
        messages.append(m.group(1))

    # -m '...' (single quoted)
    for m in re.finditer(r"-m\s+'([^']*)'", cmd):
        messages.append(m.group(1))

    # --message="..." / --message='...'
    for m in re.finditer(r'--message=\s*"((?:[^"\\]|\\.)*)"', cmd):
        messages.append(m.group(1))
    for m in re.finditer(r"--message=\s*'([^']*)'", cmd):
        messages.append(m.group(1))

    return messages


def _strip_heredoc_bodies(cmd: str) -> str:
    """Remove heredoc bodies so `git commit` text *inside* a heredoc
    (e.g. a python script printed via `python3 - <<'PY' ... PY`) is
    not misdetected as an actual commit invocation. Keep the `<<TAG`
    marker itself so surrounding shell structure remains parseable."""
    return re.sub(
        r"(<<-?\s*'?\w+'?)\s*\n.*?\n\s*\w+\b",
        r"\1",
        cmd,
        flags=re.DOTALL,
    )


def is_git_commit(cmd: str) -> bool:
    """Return True if the command invokes `git commit`.

    Two patterns are OR'd so common variants all match:
      - Strict:     only flag tokens between `git` and `commit`
                    (e.g. `git -n commit`)
      - Permissive: any token sequence between `git` and `commit`
                    (e.g. `git -C /path commit`, `git --git-dir=... commit`)

    Heredoc bodies are stripped first so `git commit` appearing inside
    a quoted script does not trigger a false positive.
    """
    stripped = _strip_heredoc_bodies(cmd)
    patterns = (
        r"\bgit\s+(?:-[^\s]+\s+)*commit\b",
        r"\bgit(?:\s+\S+)*?\s+commit\b",
    )
    return any(re.search(p, stripped) for p in patterns)


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        sys.exit(0)

    if data.get("tool_name") != "Bash":
        sys.exit(0)

    cmd = data.get("tool_input", {}).get("command", "") or ""

    # Only care about git commit (not git log, git commit-tree, etc.)
    if not is_git_commit(cmd):
        sys.exit(0)

    violations = []

    # 1) Forbidden substrings anywhere in the command
    for needle, reason in FORBIDDEN_SUBSTRINGS:
        if needle in cmd:
            violations.append(f"{reason} (found '{needle}')")

    messages = extract_messages(cmd)

    # 2) Multiline body check
    for msg in messages:
        if "\n" in msg.strip():
            violations.append(
                "multiline commit body not allowed — single-line only"
            )
            break

    # 3) Conventional prefix check (on the first/only message)
    if messages:
        first_line = messages[0].strip().split("\n", 1)[0]
        if not re.match(rf"^({CONV_TYPES})(\([^)]+\))?!?:\s+\S", first_line):
            violations.append(
                f"missing conventional-commit prefix "
                f"({CONV_TYPES}): got '{first_line[:60]}'"
            )

    if not violations:
        sys.exit(0)

    reason = (
        "Commit blocked by user's global commit rules:\n"
        + "\n".join(f"  - {v}" for v in violations)
        + "\n\nRequired format: `<type>(scope): <imperative subject>` — "
        "single line, no body, no co-author, no 'generated by', no emoji.\n"
        "See ~/.claude/skills/commit.md for full rules.\n"
        "Rewrite the commit command and try again."
    )

    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    sys.exit(0)


if __name__ == "__main__":
    main()
